{
 "title": "iostats from diskio",
 "description": "iostat data for nvme drives",
 "tags": [
  "diskio",
  "hosts",
  "controllers",
  "nvme"
 ],
 "time": { "from": "2018-12-11T16:27:58.154Z", "to": "2018-12-11T20:23:02.316Z" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"host\""
   },
   { "name": "device_type", "query": "md,nvme,sd,zd" }
  ]
 },
 "panels": [
  {
   "title": "$device_type Utilization: $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_diskstats",
     "query": "SELECT non_negative_derivative(last(\"io_time\"), 1s)  / 10 FROM \"diskio\" WHERE \"name\" =~ /(^$device_type[a-z]+$|^$device_type[_][d]|^$device_type[0-9]+)/ AND \"host\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "io_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^zd/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "$device_type IOPS: $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(last(\"reads\"), 1s) FROM \"diskio\" WHERE \"name\" =~ /^sd[a-z]+$/ AND \"host\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "reads" ], "type": "alias" }
      ],
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "writes" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "name",
       "operator": "=~",
       "value": "/(^$device_type[a-z]+$|^$device_type[_][d]|^$device_type[0-9]+)/"
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Queue Size (avgqu-sz): $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "weighted_io_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1ms" ], "type": "non_negative_derivative" },
       { "params": [ "queue size" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      {
       "condition": "AND",
       "key": "name",
       "operator": "=~",
       "value": "/(^$device_type[a-z]+$|^$device_type[_][d]|^$device_type[0-9]+)/"
      }
     ]
    }
   ]
  },
  {
   "title": "$device_type Bandwidth: $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_name $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "name",
       "operator": "=~",
       "value": "/(^$device_type[a-z]+$|^$device_type[_][d]|^$device_type[0-9]+)/"
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "$device_type Avg Latency (await): $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_diskstats",
     "query": "SELECT  ((difference(last(\"read_time\")) + difference(last(\"write_time\"))) /  (difference(last(\"reads\")) + difference(last(\"writes\")))) FROM \"diskio\" WHERE \"name\" =~ /(^$device_type[a-z]+$|^$device_type[_][d]|^$device_type[0-9]+)/ AND \"host\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "io_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^sd/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "$device_type write Avg Latency (w_await): $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_diskstats",
     "query": "SELECT difference(last(\"write_time\")) /  difference(last(\"writes\")) FROM \"diskio\" WHERE \"name\" =~ /(^$device_type[a-z]+$|^$device_type[_][d]|^$device_type[0-9]+)/ AND \"host\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "io_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^sd/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "$device_type read Avg Latency (r_await): $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_diskstats",
     "query": "SELECT difference(last(\"read_time\")) /  difference(last(\"reads\")) FROM \"diskio\" WHERE \"name\" =~ /(^$device_type[a-z]+$|^$device_type[_][d]|^$device_type[0-9]+)/ AND \"host\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "io_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^sd/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "$device_type Avg Request Size (avgrq_sz): $hostname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_diskstats",
     "query": "SELECT  ((difference(last(\"read_bytes\")) + difference(last(\"write_bytes\"))) /  (difference(last(\"reads\")) + difference(last(\"writes\")))) FROM \"diskio\" WHERE \"name\" =~ /(^$device_type[a-z]+$|^$device_type[_][d]|^$device_type[0-9]+)/ AND \"host\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "io_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^sd/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "About iostats from diskio",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "content": "# iostats from diskio collector for telegraf on Linux\nThe Linux diskio collector gathers the same information used by the _iostat_ program.\nPerformance analysts often use `iostat -x` to observe the queues for block devices.\nThis dashboard produces graphs for these queues.\n\nIn this document, queuing theory definitions are used for _servers_.\nThe diskio and iostat statistics represent a simple, single-server model.\nFor modern systems, there can be many queues and servers.\n\nThroughput graphs (IOPS and bandwidth) discriminate read and write operations based on an up-down I/O model.\nConsider a drawing where the disk is at the bottom and the computer is above the disk. \nReads flow up from disk (bottom) to computercomputer (top) and are shown in X-Y graph as positive Y values.\nWrites flow down from computer to disk and are represented as negative Y values.\nThese values can be stacked to show the the total bandwidth of both read and write to all devices.\n\n## Utilization\nWhen analyzing block I/O queues, the first filter is the utilization or busy percentage, `%util`.\nUtilization is measured as the percent of time where at least one I/O operation is queued to the device.\nIf the utilization is low (< 10%) the block device is simply not busy enough to become saturated.\n\n## IOPS\nI/O operations per second (IOPS) is a throughput measurement of the number of operations submitted\nto the I/O scheduler. The actual number of operations submitted to the device can be higher or lower\nbecause the scheduler can merge or split the operations. Some schedulers prefetch reads, which is \nnot necessarily measured here.\n\n## Average Queue Size\nThe average queue size graphs the iostat `aqu-sz` or `avgqu-sz`\nThis represents the average number of requests in the simple queue model.\n\n## Bandwidth\nBandwidth shows the bytes per second read and written to the block device.\n\n## Average Latency\nThe average latency for both read and write operations are represented by the iostat `await` values.\nFor many modern devices, the read and write latencies can vary significantly due to caching.\nTo observe these effects, read and write latencies are graphed separately, too.\nNote that latency measurements are not cumulative.\n\n## Write Average Latency\nThe write average latency as represented by the iostat `w_await` values.\n\n## Read Average latency\nThe read average latency as represented by the iostat `r_await` values.\n\n## Average Request size\nThe average request size shows the average size of all read and write operations in bytes.\nThe equivalent iostat value is `avgrq-sz` or `areq-sz`.\n"
  }
 ]
}